language: dart

dart:
  - stable

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script: dartfmt -n --set-exit-if-changed .
      name: dartfmt
    - stage: lint
      script: dartanalyzer --fatal-warnings --fatal-infos .
      name: dartanalyzer
    - stage: test
      script: pub run test .
      name: test
